spring.application.name=StudentManagementSytem
# ===============================
# MySQL Database Configuration
# ===============================
#spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=${MYSQLUSER}
#spring.datasource.password=${MYSQLPASSWORD}

#Hardcoding
spring.datasource.url=jdbc:mysql://mysql.railway.internal/3306/railway
spring.datasource.username=root
spring.datasource.password=SgyLvgjpLHxllbviGlMUVJTtqLJMfJwf




#=======================
#Localhost
#spring.datasource.url=jdbc:mysql://localhost:3306/student_management
#spring.datasource.username=root
#spring.datasource.password=@Aakash@20

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace


# ===============================
# Render Port
# ===============================
server.port=${PORT:8080}
