spring.application.name=StudentManagementSytem
# ===============================
# MySQL Database Configuration
# ===============================
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
# Driver Class Name (Modern version)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#=======================
#Localhost
#spring.datasource.url=jdbc:mysql://localhost:3306/student_management
#spring.datasource.username=root
#spring.datasource.password=@Aakash@20

# ===============================
# JPA / Hibernate
# ==============================

# Hibernate Dialect (Modern versions 6+ use this generic one for all MySQL 8+)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Additional JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace


# ===============================
# Render Port
# ===============================
server.port=${PORT:8080}
